config/routes.rb
Practiceproblemportal::Application.routes.draw do

  devise_for :instructors, controllers: {
    sessions: "instructors/sessions",
    registrations: "instructors/registrations"
  }, path: "instructors", path_names: { sign_up: 'sign_up_only' }

  devise_scope :instructor do
    get 'students_progress' => 'instructors/sessions#students_progress'
  end

  devise_for :students, controllers: {
      sessions: "students/sessions",
      registrations: "students/registrations"
  }

  get 'tags/:tag', to: 'problems#index', as: :tag

  devise_scope :student do
    get "students/:id" => "students/sessions#profile", as: :student_profile
  end

  resources :problems do
    member do
     post 'complete', to: 'problems#complete'
    end
  end

  resources :application do
    collection do
      get 'logout', to: 'application#destroy'
    end
  end

  root :to => 'problems#index'
end

app/models/problem.rb
class Problem < ActiveRecord::Base
  attr_accessible :title, :category, :difficulty, :description, :solution, :tag_list
  acts_as_taggable


end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController

  def index
    if (!student_signed_in? and !instructor_signed_in?)
      redirect_to new_student_session_path
    end
    @search = Problem.search(params[:q])
    # this is for tagging
    if params[:tag]
      @problems = Problem.tagged_with(params[:tag])
    else
      @problems = @search.result
    end
    if (student_signed_in?)
      @completion_hash = current_student.completed_problems
      if @completion_hash == nil
        current_student.completed_problems = Hash.new
        current_student.save
      end
    end
  end

  def new
    if !instructor_signed_in?
      redirect_to problems_path
      flash[:notice] = "Permission Denied"
    end
  end

  def show
    require 'coderay'
    id = params[:id]
    @problem = Problem.find(id)
    if(student_signed_in?)
      @completion_hash = current_student.completed_problems
    end
    renderer = Redcarpet::Render::HTML.new(hard_wrawp: true, prettify: true)
    @markdown = Redcarpet::Markdown.new(renderer, autolink: true, tables: true)
    #will render app/views/problems/show.<extension> by default
  end

  def create
    @problem = Problem.create!(params[:problem])
    flash[:notice] = "#{@problem.title} was successfully created."
    redirect_to problems_path #make sure this is the right route
  end

  def complete
    @completion_hash = current_student.completed_problems
    if (params[:complete] == "1")
      @completion_hash[params[:problem]] = "Complete"
    else
      @completion_hash[params[:problem]] = "In Progress"
    end
    current_student.completed_problems = @completion_hash
    current_student.save
    redirect_to problems_path
  end

  def edit
    if instructor_signed_in?
        @problem = Problem.find params[:id]
    else
      flash[:notice] = "Permission Denied"
      redirect_to problems_path
    end
  end

  def update
    modelHandler = ModelHandler.new(Problem)
    @problem = modelHandler.update(params[:id], params[:problem])
    flash[:notice] = "#{@problem.title} was successfully updated."
    redirect_to problem_path(@problem)
  end

  def destroy
    modelHandler = ModelHandler.new(Problem)
    modelHandler.destroy(params[:id])
    flash[:notice] = "Problem was successfully deleted."
    redirect_to problems_path
  end

end

app/views/problems/edit.html.erb
<div class="problem-editor">
<h1>Edit <%= @problem.title %></h1>


<%= form_for :problem, url: problem_path(@problem), :method => :put do |p| %>
  <p>
    <%= p.label :title %><br>
    <%= p.text_field :title %>
  </p>

  <p>
    <%= p.label :tag_list, "Tags (seperated by commas)" %> <br/>
    <%= p.text_field :tag_list %>
  </p>

  <p>
    <%= p.label :difficulty %><br>
    <%= p.select :difficulty, ["Hard", "Medium", "Easy"] %>
  </p>

  <p>
    <%= p.label :description %><br>
    <%= p.text_area :description, style: "width: 700px; height: 300px;" %>
  </p>

  <p>
    <%= p.label :solution %><br>
    <%= p.text_area :solution, style: "width: 700px; height: 300px;" %>
  </p>

  <p>
    <%= submit_tag 'Update Problem', class: "btn btn-warning" %>
  </p>
<% end %>
</div>

app/views/problems/index.html.erb
<html>

    <script>
      $(document).ready(function(){
        $("tr[data-link]").click(function() {
          window.location = this.dataset.link
        });
      });
    </script>
    <body>

    <div class="outer-div">

      <div class="inner-left-div" id = "problem-table">
          <div class="form-inline" align="right">
            <%= search_form_for @search do |f| %>
              <%= f.text_field :title_cont, class: 'form-control input-lg', placeholder: 'Search Problem', id:'search_problems' %>
              <%= f.submit "Search", class: 'btn btn-default btn-xs' %>
            <% end %>
          </div>
        <table class="table table-striped" id='problems-dt'>
          <thead>
            <tr>
                <th class="problem-header half-width">Title</th>
                <th class="problem-header">Difficulty</th>
                <% if @completion_hash != nil%>
                  <% if @completion_hash.length >0 %>
                    <th class="problem-header">Progress</th>
                  <% end %>
                <% end %>
                <th class="problem-header">Tags</th>
            </tr>
          </thead>
          <tbody>
            <% @problems.each do |problem| %>
            <tr>
                <td> <%= link_to "#{problem.title}", problem_path(problem) %> </td>
                <td> <%= problem.difficulty %> </td>
                <% if @completion_hash != nil%>
                  <% if @completion_hash.length >0 %>
                    <td><%= @completion_hash[problem.title] %></td>
                  <% end %>
                <% end %>
                <td> <%= raw problem.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %> </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <% if Problem.tag_counts.size > 0 %>
        <div class="inner-right-div col-lg-2 col-pull-3">
          <table class="table-bordered table table-hover top-border-change">
            <thead>
              <tr class="background-color-tags">
                <th class="background-color-fonts" style="border-bottom-width: 1px;"><span class="glyphicon glyphicon-tag" style="vertical-align:middle"></span>Tags</th>
              </tr>
            </thead>
            <tbody>
                <% Problem.tag_counts.each do |tag| %>
                  <tr data-link="<%= tag_path(tag.to_s) %>">
                    <td> <%= link_to tag, tag_path(tag.to_s) %> <span class="badge float-right"> <%= tag.taggings_count %> </span> </td>
                  </tr>
                <% end %>
            </tbody>
          </table>
        </div>
      <% end %>
    </div>

    </body>
</html>

app/views/problems/new.html.erb
<div class="problem-editor">
<h1>Create new problem</h1>
<%= flash[:notice] %>
<%= form_for :problem, url: problems_path do |p| %>
  <p>
    <%= p.label :title %><br>
    <%= p.text_field :title %>
  </p>

  <p>
    <%= p.label :tag_list, "Tags (seperated by commas)" %> <br/>
    <%= p.text_field :tag_list %>
  </p>

  <p>
    <%= p.label :difficulty %><br>
    <%= p.select :difficulty, ["Hard", "Medium", "Easy"] %>
  </p>

  <p>
    <%= p.label :description %><br>
    <%= p.text_area :description, style: "width: 700px; height: 300px;" %>
  </p>

  <p>
    <%= p.label :solution %><br>
    <%= p.text_area :solution, style: "width: 700px; height: 300px;" %>
  </p>

  <p>
    <%= submit_tag 'Create Problem', class: "btn btn-success" %>
  </p>
<% end %>
</div>

app/views/problems/show.html.erb
<div class="container">
  <script>
  $(document).ready(function(){
      $("#solution").hide();
      $("button").click(function(){
        $("#solution").toggle(500);
      });
      <% if student_signed_in? %>
        <% if !@completion_hash.has_key?(@problem.title) %>
          <% @completion_hash[@problem.title] = "In Progress" %>
        <% end %>
      <% end %>
  });
  </script>
  
  <%= link_to problems_path, class: "btn btn-default" do %>
    <i class="glyphicon glyphicon-chevron-left"></i>Back
  <% end %>

  <h2><%= @problem.title %></h2>
  <div id="question-content"
    <p>
      <%= @markdown.render(@problem.description).html_safe %>
    </p>
  </div>

  <% if instructor_signed_in? %>
    <%= link_to 'Edit', edit_problem_path(@problem), class: 'btn btn-warning btn-sm' %>
    <p></p>

    <%= button_to 'Delete', problem_path(@problem), class: 'btn btn-danger btn-sm margin-button', method: :delete, data: { confirm: 'Are you sure you want to delete this problem?' } %>
  <% end %>

  <% if student_signed_in? %>
    <%= form_tag complete_problem_path do %>
      <div style="display: inline-block">
        <%= check_box_tag :complete, 1, @completion_hash[@problem.title] == "Complete" %>
        Complete?
      </div>
      <%= hidden_field_tag :problem, @problem.title %>
      <p>
      <p>
      <%= submit_tag 'Save', class: "btn btn-success" %>
    <% end %>
  <% end %>

  <button class="btn btn-info btn-sm">Toggle Solution</button>
  <div style="background:#E3E3E3" id="solution">
    <p><%= @markdown.render(@problem.solution).html_safe %></p>
  </div>
</div>