config/routes.rb
Practiceproblemportal::Application.routes.draw do

  devise_for :instructors, controllers: {
    sessions: "instructors/sessions",
    registrations: "instructors/registrations"
  }, path: "instructors", path_names: { sign_up: 'sign_up_only' }

  devise_scope :instructor do
    get 'students_progress' => 'instructors/sessions#students_progress'
  end

  devise_for :students, controllers: {
      sessions: "students/sessions",
      registrations: "students/registrations"
  }

  get 'tags/:tag', to: 'problems#index', as: :tag

  devise_scope :student do
    get "students/:id" => "students/sessions#profile", as: :student_profile
  end

  resources :problems do
    member do
     post 'complete', to: 'problems#complete'
    end
  end

  resources :application do
    collection do
      get 'logout', to: 'application#destroy'
    end
  end

  root :to => 'problems#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Practiceproblemportal</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag "//cdn.datatables.net/plug-ings/f2c75b7247b/integration/bootstrap/3/dataTables.bootstrap.js" %>
  <script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js"></script>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "//cdn.datatables.net/plug-ings/f2c75b7247b/integration/bootstrap/3/dataTables.bootstrap.js" %>
</head>
<body>
    <%= nav_bar fixed: :top do %>
      <%= menu_group do %>
        <%= menu_item "CS61A Practice Portal", root_path %>
        <%= menu_item "Problems", problems_path %>
        <% if instructor_signed_in? %>
          <%= menu_item "Create Problem", new_problem_path %>
          <%= menu_item "View Students", students_progress_path %>
        <% end %>
        <% if student_signed_in?%>
          <%= menu_item "Profile", student_profile_path(current_student) %>
        <% end %>
      <% end %>
      <%= menu_group pull: :right do %>

        <% if !student_signed_in? and !instructor_signed_in? %>
          <%= menu_item "Sign Up", new_student_registration_path %>
          <%= drop_down "Login" do %>
            <%= link_to "Instructor Login", new_instructor_session_path, class: "btn btn-primary btn-block " %>
            <%= link_to "Student Login", new_student_session_path, class: "btn btn-success btn-block" %>
          <% end %>
        <% else %>
          <% if student_signed_in? %>
            <%= menu_item "Logout", destroy_student_session_path, method: :delete %>
          <% elsif instructor_signed_in? %>
            <%= menu_item "Logout", destroy_instructor_session_path, method: :delete %>
          <% end %>
        <% end %>

      <% end %>
    <% end %>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
</body>
</html>